### ISSUE TITLE
Advanced Query Capabilities

### ISSUE THREAD

**Issue by SergeyBarskiy** [davetimmins/ArcGIS.PCL#41]
When describing a service, Advanced Query Capabilities node is not included in the response.  Here is how it looks in the browser when hitting a service.
Advanced Query Capabilities:
Supports Statistics: true
Supports OrderBy: true
Supports Distinct: true
Supports Pagination: false
Supports TrueCurve: true

**Comment by davetimmins** [comment]
Yea, there is quite a lot of missing information from the `ServiceLayerDescriptionResponse` class. I only put in the more common properties since that response can vary between layers and services. Adding more properties in is fine, though be aware that some of the functions described are not exposed via the operations in the library e.g. statistics, curved geometry.
